<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Timetable Export</title>
    <style>
        body {
            font-family: DejaVu Sans, Arial, sans-serif;
            font-size: 12px;
            color: #1f2937;
            margin: 0;
            padding: 32px;
            background-color: #f8fafc;
        }
        h1 {
            font-size: 22px;
            margin-bottom: 4px;
            color: #111827;
        }
        .subtitle {
            font-size: 12px;
            color: #6b7280;
            margin-bottom: 24px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 24px;
        }
        th {
            background-color: #eef2ff;
            color: #312e81;
            font-weight: bold;
            padding: 10px;
            text-align: left;
            border: 1px solid #d1d5db;
        }
        td {
            padding: 10px;
            border: 1px solid #e5e7eb;
            vertical-align: top;
        }
        .footer {
            margin-top: 32px;
            font-size: 10px;
            color: #6b7280;
            text-align: right;
        }
        .badge {
            display: inline-block;
            padding: 2px 8px;
            font-size: 10px;
            border-radius: 999px;
            background-color: #e0e7ff;
            color: #3730a3;
        }
    </style>
</head>
<body>
    <header>
        <h1>Timetable Export</h1>
        <div class="subtitle">
            Range: {{ $range['start'] }} &mdash; {{ $range['end'] }}<br>
            Generated at: {{ $generatedAt }}
        </div>
    </header>

    <table>
        <thead>
            <tr>
                <th style="width: 22%;">Student</th>
                <th style="width: 20%;">Teacher</th>
                <th style="width: 18%;">Course</th>
                <th style="width: 20%;">Date</th>
                <th style="width: 12%;">Time</th>
                <th style="width: 8%;">Timezone</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($events as $event)
                <tr>
                    <td>{{ $event['student'] ?? '—' }}</td>
                    <td>{{ $event['teacher'] ?? '—' }}</td>
                    <td>
                        <span class="badge">{{ $event['course_name'] }}</span>
                    </td>
                    <td>{{ $event['date'] }}</td>
                    <td>{{ $event['time'] }}</td>
                    <td>{{ $event['timezone'] }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="6" style="text-align: center; font-style: italic; color: #6b7280;">
                        No events found for the selected period.
                    </td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Generated by Alarabiya Academy &bullet; {{ config('app.name') }}
    </div>
</body>
</html>

